[package]
name = "marty"
version = "0.1.0"
edition = "2021"

authors = ["ph"]

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
arboard = "3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
